name: proteoparc-v1.1
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - mafft=7.525
  - r-base=4.2
  - r-ggplot2=3.4.4
  - r-dplyr=1.1.4
  - r-reshape2=1.4.4
  - r-tidyr=1.3.1
  - python=3.12.3
  - pip=24.0
  - pip:
      - bio==1.7.1
      - pandas==2.2.2
      - requests==2.32.3